nginx:
  build: infra/containers/nginx
  links:
    - moodle
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - moodle
    - learninglocker
  volumes:
    - ./infra/containers/nginx/config:/etc/nginx/conf.d/
    - ./infra/containers/nginx/config:/etc/nginx/conf.d/
    - ./infra/containers/nginx/log:/var/log/nginx

moodle:
  build: infra/containers/moodle
  links:
    - mariadb
    - memcached
    - learninglocker
  ports:
    - "9000:9000"
  volumes:
    - ./src/broad-ecos-moodle-mod:/var/www/html/moodle/mod/broadecosmod
    - ./infra/containers/moodle/config/config.php:/var/www/html/moodle/config.php
    - ./infra/containers/moodle/data/moodledata:/var/www/moodledata
  dns: 172.17.42.1

mariadb:
  build: infra/containers/mariadb
  ports:
    - "3307:3306"
  volumes:
    - ./infra/containers/mariadb/log:/var/log/mysql
    - ./infra/containers/mariadb/data:/var/lib/mysql
  env_file:
    - ./infra/envvars/mariadb.env

memcached:
  build: infra/containers/memcached
  ports:
    - "11211:11211"

learninglocker:
  build: infra/containers/learninglocker
  ports:
    - "8079:80"
    - "27018:27017"
  volumes:
    - ./infra/containers/learninglocker/data/data:/data/db

redis:
  build: infra/containers/redis
  ports:
    - "6379:6379"

#postgresql:
#  build: infra/containers/postgresql
#  ports:
#    - "5433:5432"
#  volumes:
#    - ./infra/containers/postgresql/data:/var/lib/postgresql
#  env_file:
#    - ./infra/envvars/postgresql.env

mongodb:
  build: infra/containers/mongodb
  volumes:
    - ./infra/containers/mongodb/data:/data
  ports:
    - "27017:27017"

#rankr:
#  build: infra/containers/rankr
#  links:
#    - mongodb
#  ports:
#    - "8090:8090"
#  volumes:
#    - ./src/rankr2/build/libs/rankr-2.0.jar:/opt/app.jar
#  env_file:
#    - ./infra/envvars/broad_auth.env
#  dns: 172.17.42.1
