nginx:
  build: docker/nginx
  links:
    - moodle
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - moodle
  volumes:
    - ./config/nginx:/etc/nginx/conf.d/
    - ./log/nginx:/var/log/nginx

moodle:
  build: docker/moodle
  links:
    - mariadb
    - memcached
#    - broadauth
  ports:
    - "9000:9000"
  volumes:
    - ./src/broad-ecos-moodle-mod:/var/www/html/moodle/mod/broadecosmod
    - ./config/moodle/config.php:/var/www/html/moodle/config.php

mariadb:
  build: docker/mariadb
  ports:
    - "3307:3306"
  volumes:
    - ./log/mariadb:/var/log/mysql
    - ./data/mariadb:/var/lib/mysql
  env_file:
    - ./envvars/mariadb.env

mongodb:
  build: docker/mongodb
  volumes:
    - ./data/mongodb:/data
  ports:
    - "27017:27017"

memcached:
  build: docker/memcached
  ports:
    - "11211:11211"

redis:
  build: docker/redis
  ports:
    - "6379:6379"

#postgresql:
#  build: docker/broad/postgresql
#  ports:
#    - "5433:5432"
#  volumes:
#    - ./data/broad/postgresql:/var/lib/postgresql
#  env_file:
#    - ./envvars/postgresql.env

#broadauth:
#  build: docker/broad/auth
#  links:
#    - postgresql
#  ports:
#    - "9999:9999"
#  volumes:
#    - ./src/broad-ecos-auth-service/build/libs/demo-0.0.1.jar:/opt/app.jar
#  env_file:
#    - ./envvars/broad/auth.env
