nginx:
  build: docker/nginx
  links:
    - moodle
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - moodle
  volumes:
    - config/nginx:/etc/nginx/conf.d/
    - log/nginx:/var/log/nginx

moodle:
  build: docker/moodle
  links:
    - mariadb
    - memcached
  ports:
    - "9000:9000"
  volumes:
    - src/broad-ecos-moodle-mod:/var/www/html/moodle/mod/broadecosmod

mariadb:
  build: docker/mariadb
  ports:
    - "3307:3306"
  volumes:
    - log/mariadb:/var/log/mysql
    - data/mariadb:/var/lib/mysql
  env_file: envvars/mariadb.env

memcached:
  build: docker/memcached
  ports:
    - "11211:11211"
