nginx:
  build: docker/nginx
  links:
    - phpfpm
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - phpfpm
  volumes:
    - config/nginx:/etc/nginx/conf.d/
    - log/nginx:/var/log/nginx
phpfpm:
  build: docker/phpfpm
  links:
    - mariadb
    - memcached
  ports:
    - "9000:9000"
  volumes:
    - src/php:/var/www/html
mariadb:
  build: docker/mariadb
  ports:
    - "3307:3306"
  volumes:
    - log/mariadb:/var/log/mysql
    - data/mariadb:/var/lib/mysql
  environment:
    DB_ADMIN_PASS: pass
memcached:
  build: docker/memcached
  ports:
    - "11211:11211"
