FROM php:fpm
MAINTAINER Welington Veiga <welington.veiga@gmail.com>

# PHP config
ADD ./config/php.ini /usr/local/etc/php/

# Install modules
# Install PHP modules
RUN apt-get update \
&& apt-get install -y zlib1g-dev \
 libxml2-dev \
 libpng12-dev \
 libfreetype6-dev \
 libjpeg62-turbo-dev \
 libicu-dev \
 libcurl4-gnutls-dev \
 g++ \
 ghostscript \
 graphviz \
 aspell \
 supervisor \
 unzip \
&& rm -r /var/lib/apt/lists/* \
&& docker-php-ext-configure gd \
 --with-freetype-dir=/usr/include/ \
 --with-gd-dir=usr/include/ \
&& docker-php-ext-install zip \
 mysqli \
 gd \
 mbstring \
 xmlrpc \
 soap \
 intl \
 opcache \
 curl 

# Download and placing moodle
ADD ./vendor /opt
RUN unzip /opt/learninglocker.zip -d /var/www \
&& rm -Rf /var/www/html/learninglocker/ \
&& mv /var/www/learninglocker /var/www/html/learninglocker \
&& rm  /var/www/html/learninglocker/app/config/database.php \
&& chmod -R 0777 /var/www/ \
&& chown -R root:root /var/www/


RUN  apt-get update  && \
	apt-get install -y git
RUN cd /var/www/html/learninglocker/ && \
php -r "readfile('https://getcomposer.org/installer');" | php && \
php composer.phar install --no-interaction --no-dev && \
php artisan migrate


VOLUME /var/www/html
CMD ["php-fpm"]

