nginx:
  build: nginx-fpm
  links:
    - phpfpm
  ports:
    - "8080:80"
  volumes_from:
    - htdocs
phpfpm:
  build: php-5.6-fpm-custom
  volumes_from:
    - htdocs
    - db
db:
  image: mariadb
  volumes:
    - /var/run/mysqld
  environment:
    MYSQL_ROOT_PASSWORD: change_this
htdocs:
  image: busybox
  stdin_open: true
  volumes:
    - htdocs:/var/www/html
