#!/bin/bash
# Make sure we're not confused by old, incompletely-shutdown httpd
# context after restarting the container. httpd won't start correctly
# if it thinks it is already running.
rm -rf /run/httpd/*

# need to create directories per /usr/lib/tmpfiles.d/httpd.conf
## d /run/httpd   710 root apache
## d /run/httpd/htcacheclean   700 apache apache

mkdir -p /run/httpd/htcacheclean
chmod 710 /run/httpd
chmod 700 /run/httpd/htcacheclean

chown root:apache /run/httpd
chown apache:apache /run/httpd/htcacheclean

exec /usr/sbin/apachectl -D FOREGROUND & exec /usr/bin/mongod